apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: Service_B
    namespace: "{{ .Release.Namespace }}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: Service_B
    template:
      metadata:
        name: Service_B
      spec:
        containers:
        - env:
          - name: tester
            value: B
          - name: foo
            value: Foo
          - name: db_url
            value: local_url
          image: "alpine:latest"
          imagePullPolicy: Always
          name: "Service_B-container"
          ports:
          - containerPort: 8080
        imagePullSecrets:
        - name: regcred
- apiVersion: v1
  kind: Service
  metadata:
    name: Service_B
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    type: ClusterIP
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "{{ .Release.Name }}-Service_B"
kind: List
