---
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: Service A
    namespace: apps
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: Service A
    template:
      metadata:
        name: Service A
      spec:
        containers:
        - env:
          - name: tester
            value: tester
          - name: foo
            value: bar
          - name: global_url
            value: "{{ .Global.url }}"
          image: "alpine:3.14"
          imagePullPolicy: Always
          name: web
          ports:
          - containerPort: 80
        imagePullSecrets:
        - name: regcred
- apiVersion: v1
  kind: Service
  metadata:
    name: Service A
  spec:
    ports:
    - port: 80
      targetPort: 80
    type: ClusterIP
kind: List

---
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: Service B
    namespace: apps
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: Service B
    template:
      metadata:
        name: Service B
      spec:
        containers:
        - env:
          - name: tester
            value: Service B
          - name: db_url
            value: "{{ .Values.global.db.url }}"
          - name: global_url
            value: "{{ .Global.url }}"
          image: "alpine:3.14"
          imagePullPolicy: Always
          name: web
          ports:
          - containerPort: 80
        imagePullSecrets:
        - name: regcred
- apiVersion: v1
  kind: Service
  metadata:
    name: Service B
  spec:
    ports:
    - port: 80
      targetPort: 80
    type: ClusterIP
kind: List
