apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: "second-service"
    name: "second-service"
    namespace: "{{ .Release.Namespace }}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "second-service"
    template:
      metadata:
        labels:
          app: "second-service"
        name: "second-service"
      spec:
        containers:
        - env:
          - name: tester
            value: B
          - name: foo
            value: Foo
          - name: db_url
            value: local_url
          envFrom:
          - secretRef:
              name: testsecret
          image: "alpine:3.15"
          imagePullPolicy: IfNotPresent
          name: "second-service-container"
          ports:
          - containerPort: 8080
            name: http
        imagePullSecrets:
        - name: regcred
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "second-service"
    name: "second-service"
  spec:
    ports:
    - name: http
      port: 8080
      targetPort: 8080
    selector:
      app: "second-service"
    type: ClusterIP
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "{{ .Release.Name }}-second-service"
- apiVersion: v1
  data:
    username: YWRtaW4=
    password: MWYyZDFlMmU2N2Rm
  type: Opaque
  kind: Secret
  metadata:
    name: testsecret
kind: List
