apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: Service A
    namespace: apps
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: Service A
    template:
      metadata:
        name: Service A
      spec:
        containers:
        - env:
          - name: tester
            value: tester
          - name: foo
            value: bar
          - name: global_url
            value: url
          image: "alpine:3.14"
          imagePullPolicy: Always
          name: web
          ports:
          - containerPort: 80
        imagePullSecrets:
        - name: regcred
- apiVersion: v1
  kind: Service
  metadata:
    name: Service A
  spec:
    ports:
    - port: 80
      targetPort: 80
    type: ClusterIP
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "RELEASE-NAME-Service A"
kind: List
