apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  jobTemplate:
    metadata:
      name: hello
    spec:
      template:
        metadata:
          name: hello
        spec:
          containers:
            - command:
                - /bin/bash
                - "-c"
                - "date; echo Hello from the Kubernetes cluster"
              image: busybox
              name: hello
          restartPolicy: OnFailure
  schedule: "*/1  * * * *"
