apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: "reactive-s3-server"
    name: "reactive-s3-server"
    namespace: "{{ .Release.Namespace }}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "reactive-s3-server"
    template:
      metadata:
        labels:
          app: "reactive-s3-server"
        name: "reactive-s3-server"
      spec:
        containers:
        - env:
          - name: LOCALSTACK_URL
            value: "http://localstack.default.svc:4566"
          - name: S3_BUCKET
            value: bucket
          - name: SPRING_PROFILES_ACTIVE
            value: compose
          image: "reactive-file-server:1.0"
          imagePullPolicy: IfNotPresent
          name: "reactive-s3-server-container"
          ports:
          - containerPort: 9000
            name: http
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "reactive-s3-server"
    name: "reactive-s3-server"
  spec:
    ports:
    - name: http
      port: 9000
      targetPort: 9000
    selector:
      app: "reactive-s3-server"
    type: ClusterIP
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "{{ .Release.Name }}-reactive-s3-server"
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    labels:
      app: "reactive-s3-server"
    name: "reactive-s3-server"
    namespace: "{{ .Release.Namespace }}"
  spec:
    rules:
    - host: "reactive-server.localhost"
      http:
        paths:
        - backend:
            service:
              name: "reactive-s3-server"
              port:
                number: 9000
          path: "/*"
          pathType: Prefix
kind: List
