apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: "hello-service"
    name: "hello-service"
    namespace: "{{ .Release.Namespace }}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "hello-service"
    template:
      metadata:
        labels:
          app: "hello-service"
        name: "hello-service"
      spec:
        containers:
        - env:
          - name: tester
            value: Tester
          - name: foo
            value: bar
          - name: db_url
            value: local_url
          image: "hello-service:1.0.0"
          imagePullPolicy: IfNotPresent
          name: "hello-service-container"
          ports:
          - containerPort: 8080
            name: http
        imagePullSecrets:
        - name: regcred
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "hello-service"
    name: "hello-service"
  spec:
    ports:
    - name: http
      port: 8080
      targetPort: 8080
    selector:
      app: "hello-service"
    type: ClusterIP
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "{{ .Release.Name }}-hello-service"
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    labels:
      app: "hello-service"
    name: "hello-service"
    namespace: "{{ .Release.Namespace }}"
  spec:
    rules:
    - host: "hello-service.test.de"
      http:
        paths:
        - backend:
            service:
              name: "hello-service"
              port:
                number: 8080
          path: "/*"
          pathType: Prefix
kind: List
