apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: Service_A
    namespace: "{{ .Release.Namespace }}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: Service_A
    template:
      metadata:
        name: Service_A
      spec:
        containers:
        - env:
          - name: tester
            value: Tester
          - name: foo
            value: bar
          - name: db_url
            value: local_url
          image: "alpine:3.14"
          imagePullPolicy: Always
          name: "Service_A-container"
          ports:
          - containerPort: 8080
        imagePullSecrets:
        - name: regcred
- apiVersion: v1
  kind: Service
  metadata:
    name: Service_A
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    type: ClusterIP
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "{{ .Release.Name }}-Service_A"
kind: List
