apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: "reactive-client"
    name: "reactive-client"
    namespace: "{{ .Release.Namespace }}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "reactive-client"
    template:
      metadata:
        labels:
          app: "reactive-client"
          time: "{{ now | unixEpoch }}"
        name: "reactive-client"
      spec:
        containers:
        - env:
          - name: SERVER_URL
            value: "http://reactive-server.default.svc:9000"
          - name: SPRING_PROFILES_ACTIVE
            value: compose
          image: "reactive-client:1.0"
          imagePullPolicy: IfNotPresent
          name: "reactive-client-container"
          ports:
          - containerPort: 9001
            name: http
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "reactive-client"
    name: "reactive-client"
  spec:
    ports:
    - name: http
      port: 9001
      targetPort: 9001
    selector:
      app: "reactive-client"
    type: ClusterIP
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "{{ .Release.Name }}-reactive-client"
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    labels:
      app: "reactive-client"
    name: "reactive-client"
    namespace: "{{ .Release.Namespace }}"
  spec:
    rules:
    - host: "reactive-client.localhost"
      http:
        paths:
        - backend:
            service:
              name: "reactive-client"
              port:
                number: 9001
          path: /
          pathType: Prefix
kind: List
