{
 "title": "custom-metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Server total tranfsered bytes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_transfered_file_bytes_total{instance=\"http://reactive-server.default.svc\"} / 1000 / 1000"
    }
   ]
  },
  {
   "title": "Server last transfered bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "last_transfered_file_bytes{instance=\"http://reactive-server.default.svc\"} / 1000000"
    }
   ]
  },
  {
   "title": "Client store bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "last_stored_chunk_bytes{instance=\"http://reactive-client.default.svc\"}"
    }
   ]
  }
 ]
}