localstack:
  extraEnvVars:
    - name: SERVICES
      value: "s3"
    - name: LS_LOG
      value: "ALL"
    - name: KMS_SEED_PATH
      value: "/init/seed.yaml"
    - name: DOCKER_HOST
      value: unix:///var/run/docker.sock
  debug: true
  enableStartupScripts: true
  nameOverride: "localstack"
  #fullnameOverride: "localstack-full"
  seedKms: false
  enableDockerDaemon: true
  podSecurityContext:
    fsGroup: 412
  ingress:
    enabled: true
    hosts:
      - host: "*.localstack.localhost"
        paths:
          - path: /
            backend:
              serviceName: localstack
              servicePort: 4566
      - host: "localstack.localhost"
        paths:
          - path: /
            backend:
              serviceName: localstack
              servicePort: 4566